### ISSUE TITLE
Choose scaling factors for pre-built version

### ISSUE THREAD

**Issue by timtroendle** [timtroendle/euro-calliope#22]
Currently, all units are in `MW`, `EUR`, and `km2`. For models on the regional scale that run for one year, these scaling factors are not ideal. I found the following factors to work well in this case:

```yaml
scaling-factors:
    power: 0.00001 # from MW to 100 GW
    area: 0.0001 # from km2 to 10000 km2
    monetary: 0.000000001 # from EUR to 1000 Mio EUR
```

Also, when adjusting these factors, we should communicate that they are chosen in order to work well for the regional resolution and one year of timeseries.
